version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  fluent:
    image: fluent/fluentd:v1.10-1
    volumes:
      - ./config/fluentd.conf:/fluentd/etc/fluent.conf
      - logs:/opt/logs/:ro
  grok_exporter:
    image: magentaaps/grok_exporter:latest-rc
    command: -config /opt/grok_exporter.conf
    ports:
      - 9144:9144
    volumes:
      - ./config/grok_exporter.conf:/opt/grok_exporter.conf
  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - logs:/usr/local/apache2/logs


volumes:
  prometheus-data:
  example-logs:
  logs:
